# 🏍️ Predicción de Ganadores en MotoGP
## Proyecto de Machine Learning — Bootcamp Ironhack Data Analytics

**Autor:** Juan Boberg  
**Fecha:** Mayo 2026  
**Objetivo:** Clasificar si un piloto será el **top ganador de una temporada** en la categoría MotoGP™ (clasificación binaria supervisada).

---

### Estructura del proyecto

| Fase | Contenido |
|------|-----------|
| **Día 1** | Selección del tema y carga de datos |
| **Día 2** | Exploración, limpieza y feature engineering |
| **Día 3** | Entrenamiento y comparación de modelos base |
| **Día 4** | Optimización con GridSearchCV y conclusiones finales |

---

---
## 📅 Día 1 — Selección del Tema y Carga de Datos

### Problema de negocio

El dataset original solo contiene información de **ganadores de carrera**, no de todos los participantes. Esto impide predecir el resultado exacto de cada carrera (no hay clase "perdedor"). Por ello, reformulamos el problema:

> **¿Puede un modelo de ML predecir si un piloto será el máximo ganador de una temporada?**

- **Variable objetivo:** `is_top_winner` → `1` si el piloto tiene el mayor nº de victorias en esa temporada, `0` en caso contrario.
- **Tipo de problema:** Clasificación binaria supervisada.

### Fuentes de datos

Se utilizan **7 archivos CSV** de Kaggle con datos históricos de MotoGP (1949–2022).

In [2]:
import os
os.listdir('archive (1)')

['constructure-world-championship.csv',
 'grand-prix-events-held.csv',
 'grand-prix-race-winners.csv',
 'riders-finishing-positions.csv',
 'riders-info.csv',
 'same-nation-podium-lockouts.csv']

In [3]:
os.listdir('archive (2)')

['circuit_data.csv']

### Descripción de los datasets

| Variable | Dataset | Contenido |
|----------|---------|-----------|
| `df`  | `constructure-world-championship.csv` | Campeonato de constructores |
| `df2` | `grand-prix-events-held.csv` | Eventos y GPs celebrados |
| `df3` | `grand-prix-race-winners.csv` | ⭐ **Dataset principal** — ganadores de carrera (3.083 registros, 1949–2022) |
| `df4` | `riders-finishing-positions.csv` | Historial acumulado de posiciones por piloto |
| `df5` | `riders-info.csv` | Información adicional de pilotos |
| `df6` | `same-nation-podium-lockouts.csv` | Podios dominados por un mismo país |
| `df7` | `circuit_data.csv` | Datos técnicos de circuitos |

In [4]:
#importar datsets 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#cargar datasets
df = pd.read_csv('archive (1)/constructure-world-championship.csv')
df2 = pd.read_csv('archive (1)/grand-prix-events-held.csv')
df3 = pd.read_csv('archive (1)/grand-prix-race-winners.csv')
df4 = pd.read_csv('archive (1)/riders-finishing-positions.csv')
df5 = pd.read_csv('archive (1)/riders-info.csv')
df6 = pd.read_csv('archive (1)/same-nation-podium-lockouts.csv')
df7 = pd.read_csv('archive (2)/circuit_data.csv')

### Vista previa de los datasets clave

`df4` contiene el historial acumulado de posiciones de cada piloto a lo largo de toda su carrera:

In [5]:
df4.head()

,Rider,Victories,NumberofSecond,NumberofThird,Numberof4th,Numberof5th,Numberof6th,Country
0,Giacomo Agostini,122,67,53,48,34,24,IT
1,Valentino Rossi,115,52,47,38,30,21,IT
2,Angel Nieto,90,51,40,35,25,21,ES
3,Marc Marquez,85,44,36,28,23,21,ES
4,Mike Hailwood,76,41,33,26,22,20,GB

`df3` es el dataset principal: un registro por carrera ganada, con piloto, constructor, circuito y temporada:

In [6]:
df3.head()

,Circuit,Class,Constructor,Country,Rider,Season
0,Circuit Of The Americas,Moto3™,KTM,ES,Jaume Masia,2022
1,Circuit Of The Americas,Moto2™,Kalex,IT,Tony Arbolino,2022
2,Circuit Of The Americas,MotoGP™,Ducati,IT,Enea Bastianini,2022
3,Termas de Río Hondo,Moto3™,GASGAS,ES,Sergio Garcia,2022
4,Termas de Río Hondo,MotoGP™,Aprilia,ES,Aleix Espargaro,2022

In [7]:
df5.head()

,Riders All Time in All Classes,Victories,2nd places,3rd places,Pole positions from '74 to 2022,Race fastest lap to 2022,World Championships
0,AGOSTINI Giacomo,122,35.0,2.0,9.0,117.0,15.0
1,ROSSI Valentino,115,67.0,53.0,65.0,96.0,9.0
2,NIETO Angel,90,35.0,14.0,34.0,81.0,13.0
3,MARQUEZ Marc,85,36.0,17.0,90.0,75.0,8.0
4,HAILWOOD Mike,76,25.0,11.0,NaN,79.0,9.0

`df7` contiene datos técnicos de los circuitos (longitud, curvas, recta más larga, etc.):

In [8]:
df7.head

<bound method NDFrame.head of                                   Name           Location Country  \
0     Circuito de Jerez - Ángel Nieto    36.7081,-6.0345      ES
1              Circuit Of The Americas   30.1328,-97.6368      US
2                  Termas de Río Hondo  -27.4875,-64.9471      AR
3   Autódromo Internacional do Algarve    37.2277,-8.6267      PT
4         Lusail International Circuit    25.4713,51.4909      QA
..                                 ...                ...     ...
66                            Hedemora    60.2859,15.9959      SE
67                               Reims     49.2542,3.9736      FR
68                               Berne     46.9428,7.4688      CH
69                            Schotten     50.4901,9.1436      DE
70                                Albi     43.9285,2.1066      FR

   Pole Position  Length in meters Width in meters  Right Corners  \
0           Left              4423              11              8
1          Right              5513              15              9
2           Left              4806              16              9
3           Left              4592              18              9
4           Left              5380              12             10
..           ...               ...             ...            ...
66       Unknown              1538             7-8              4
67       Unknown              8302            8-12              4
68       Unknown              2660         6.1-7.1              4
69       Unknown              2575             6-8              2
70       Unknown              3565           10-12              7

    Left Corners  Longest Straight  Constructed  Modified
0              5               607         1986      2002
1             11              1200         2012      2012
2              5              1076         2008      2013
3              6               970         2008      2008
4              6              1068         2004      2004
..           ...               ...          ...       ...
66             4               575         1949      1967
67             6              1650         1926      1972
68             3               600         1931      1954
69             8               150         1950      2016
70             5               800         1959      2014

[71 rows x 11 columns]>

---
## 📅 Día 2 — Exploración, Limpieza y Feature Engineering

El objetivo de esta fase es transformar los datos brutos en un dataset estructurado y limpio, listo para entrenar modelos de ML.

### 2.1 Exploración inicial del dataset principal (`df3`)

Inspeccionamos la estructura de `df3` para identificar tipos de datos, valores nulos y el tamaño del dataset.

In [9]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 3083 entries, 0 to 3082
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Circuit      3083 non-null   str
 1   Class        3083 non-null   str
 2   Constructor  3055 non-null   str
 3   Country      3018 non-null   str
 4   Rider        3083 non-null   str
 5   Season       3083 non-null   int64
dtypes: int64(1), str(5)
memory usage: 144.6 KB

### 2.2 Limpieza de valores nulos

`df3` tiene **28 nulos en Constructor** y **65 en Country**. Dado que corresponden a equipos satélite históricos o carreras con datos incompletos, los rellenamos con `'Unknown'` para no perder esas filas.

In [10]:
#Constructor cuando es null es igual a Unknown
df3['Constructor'] = df3['Constructor'].fillna('Unknown')
print(df3['Constructor'].isnull().sum())

0

In [11]:
# País cuando es null es igual a Unknown
df3['Country'] = df3['Country'].fillna('Unknown')
print(df3['Country'].isnull().sum())

0

### 2.3 Filtrado por categoría MotoGP™

El dataset incluye múltiples categorías (Moto3™, Moto2™, 125cc, etc.). Filtramos únicamente la clase **MotoGP™** para trabajar con la categoría reina del mundial.

In [12]:
df3['Class'].unique()

<StringArray>
[ 'Moto3™',  'Moto2™', 'MotoGP™',  'MotoE™',   '125cc',   '250cc',    '80cc',
    '50cc',   '350cc']
Length: 9, dtype: str

In [13]:
# Filtrar df3 para classe 'MotoGP'
df3_motogp = df3[df3['Class'] == 'MotoGP™']
print(df3_motogp.shape)

(871, 6)

Resultado: de 3.083 registros totales pasamos a **871 registros** de MotoGP™ (desde la creación de la categoría en 2002 hasta 2022).

---

### 2.4 Feature Engineering

Esta es la fase más importante del proyecto. Construimos las features y la variable objetivo desde cero.

#### Paso 1 — Victorias por piloto y temporada

Agrupamos los registros de victorias para obtener cuántas carreras ganó cada piloto en cada temporada.

In [14]:
victories = df3_motogp.groupby(['Rider', 'Season']).size().reset_index(name='Victories')
victories.head()

            Rider  Season  Victories
0   Alan Shepherd    1962          1
1  Alberto Pagani    1969          1
2  Alberto Pagani    1971          1
3  Alberto Pagani    1972          1
4    Alberto Puig    1995          1

#### Paso 2 — Máximo de victorias por temporada

Identificamos cuál fue el máximo número de victorias conseguido por cualquier piloto en cada año. Este será el umbral para definir al "top ganador".

In [15]:
max_victories = victories.groupby('Season')['Victories'].max().reset_index()
max_victories.head()

   Season  Victories
0    1949          2
1    1950          3
2    1951          4
3    1952          2
4    1953          2

#### Paso 3 — Creación de la variable objetivo `is_top_winner`

Hacemos un merge con el máximo de victorias y creamos el **target binario**: `1` si el piloto igualó el máximo de victorias de esa temporada, `0` en caso contrario.

> ⚠️ **Nota sobre el desbalance de clases:** dado que solo hay un campeón por temporada, la clase positiva (`is_top_winner = 1`) será una minoría significativa (~6.5% del total). Esto es un reto clave del proyecto.

In [16]:
victories = victories.merge(max_victories, on='Season', suffixes=('', '_max'))
victories['is_top_winner'] = (victories['Victories'] == victories['Victories_max']).astype(int)
victories.head()

            Rider  Season  Victories  Victories_max  is_top_winner
0   Alan Shepherd    1962          1              5              0
1  Alberto Pagani    1969          1             10              0
2  Alberto Pagani    1971          1              8              0
3  Alberto Pagani    1972          1             11              0
4    Alberto Puig    1995          1              7              0

#### Paso 4 — Enriquecimiento con historial histórico del piloto

Hacemos un merge con `df4` para añadir features del historial acumulado de cada piloto (victorias totales, podios, etc.). Estas features dan al modelo contexto sobre el talento histórico del piloto.

In [17]:
df4.columns

Index(['Rider', 'Victories', 'NumberofSecond', 'NumberofThird', 'Numberof4th',
       'Numberof5th', 'Numberof6th', 'Country'],
      dtype='str')

In [18]:
df_model = victories.merge(df4, on='Rider', how='left')
df_model.head()

,Rider,Season,Victories_x,Victories_max,is_top_winner,Victories_y,NumberofSecond,NumberofThird,Numberof4th,Numberof5th,Numberof6th,Country
0,Alan Shepherd,1962,1,5,0,2.0,4.0,4.0,5.0,5.0,4.0,GB
1,Alberto Pagani,1969,1,10,0,3.0,4.0,4.0,5.0,5.0,4.0,IT
2,Alberto Pagani,1971,1,8,0,3.0,4.0,4.0,5.0,5.0,4.0,IT
3,Alberto Pagani,1972,1,11,0,3.0,4.0,4.0,5.0,5.0,4.0,IT
4,Alberto Puig,1995,1,7,0,1.0,2.0,2.0,2.0,3.0,3.0,ES

In [19]:
df_model.columns

Index(['Rider', 'Season', 'Victories_x', 'Victories_max', 'is_top_winner',
       'Victories_y', 'NumberofSecond', 'NumberofThird', 'Numberof4th',
       'Numberof5th', 'Numberof6th', 'Country'],
      dtype='str')

#### Paso 5 — Eliminación de filas con valores nulos

Eliminamos las filas donde el piloto no tiene historial en `df4` (merge sin correspondencia). Esto reduce el dataset pero garantiza que todas las features estén completas.

In [20]:
# Eliminar columnas innecesarias
df_model = df_model.dropna()
print(df_model.shape)

(304, 12)

### 2.5 Preparación para el entrenamiento

Separamos features (`X`) de la variable objetivo (`y`), realizamos el **train-test split 80/20** y aplicamos **variables dummy** para las columnas categóricas (Rider, Country).

In [21]:
#Definir X e y
X = df_model.drop(columns=['is_top_winner'])
y = df_model['is_top_winner']
print(X.shape)
print(y.shape)

(304, 11)
(304,)

In [22]:
#Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
#Dummy variables
X_train = pd.get_dummies(X_train, drop_first=True)
X_test = pd.get_dummies(X_test, drop_first=True)
#Asegurar que ambas matrices tengan las mismas columnas
X_train, X_test = X_train.align(X_test, join='left', axis=1
, fill_value=0)
print(X_train.shape)

(243, 130)

> **Por qué `align(join='left')`:** al aplicar `get_dummies` por separado en train y test, pueden aparecer categorías distintas. Con `align` forzamos que `X_test` tenga exactamente las mismas columnas que `X_train`, rellenando con 0 las que no existan en test.

---

---
## 📅 Día 3 — Entrenamiento y Comparación de Modelos Base

Entrenamos tres modelos con parámetros por defecto para obtener una línea base de rendimiento antes de optimizar.

**Métrica prioritaria: Recall de la clase 1 (top winner)**  
En problemas de desbalance, el *recall* de la clase minoritaria es más informativo que el *accuracy* global, ya que mide cuántos ganadores reales el modelo es capaz de detectar.

### KNN (K-Nearest Neighbors) — Baseline

Modelo simple de vecinos cercanos. Susceptible al desbalance porque en un espacio con muchos ejemplos de clase 0, los vecinos más cercanos suelen ser no-ganadores.

In [32]:
# Evaluar modelo KNN
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85        46
           1       0.53      0.53      0.53        15

    accuracy                           0.77        61
   macro avg       0.69      0.69      0.69        61
weighted avg       0.77      0.77      0.77        61

### AdaBoost — Ensemble adaptativo

AdaBoost asigna mayor peso a los ejemplos mal clasificados en cada iteración. Esto lo hace especialmente efectivo con clases minoritarias, ya que el modelo aprende a prestar más atención a los ganadores.

In [33]:
# Evaluar modelo AdaBoost
from sklearn.ensemble import AdaBoostClassifier
adaboost_model = AdaBoostClassifier(random_state=42)
adaboost_model.fit(X_train, y_train)
y_pred_adaboost = adaboost_model.predict(X_test)
print(classification_report(y_test, y_pred_adaboost))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        46
           1       0.88      1.00      0.94        15

    accuracy                           0.97        61
   macro avg       0.94      0.98      0.96        61
weighted avg       0.97      0.97      0.97        61

### Gradient Boosting — Ensemble secuencial

Entrena árboles pequeños de forma secuencial, donde cada árbol corrige los errores del anterior minimizando una función de pérdida. Ofrece un excelente balance entre bias y varianza.

In [34]:
# Evaluar modelo Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier
gradient_boosting_model = GradientBoostingClassifier(random_state=42)
gradient_boosting_model.fit(X_train, y_train)
y_pred_gradient_boosting = gradient_boosting_model.predict(X_test)
print(classification_report(y_test, y_pred_gradient_boosting))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.83      1.00      0.91        15

    accuracy                           0.95        61
   macro avg       0.92      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

### Random Forest — Ensemble por votación

Entrena múltiples árboles de decisión en subconjuntos aleatorios del dataset y combina sus predicciones por votación. Más resistente al overfitting que un árbol individual, pero puede sufrir más con el desbalance que los métodos boosting.

In [ ]:
# Evaluar modelo Random Forest
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf_base = rf_model.predict(X_test)
print(classification_report(y_test, y_pred_rf_base))

### Resumen comparativo — Modelos base

| Modelo | Accuracy | Recall clase 1 | F1 clase 1 | Notas |
|--------|----------|----------------|------------|-------|
| KNN | 0.77 | 0.53 | 0.53 | Sufre por el desbalance |
| Random Forest | ~0.85 | ~0.70 | ~0.71 | Mejor que KNN, peor que boosting |
| AdaBoost | **0.97** | **1.00** | **0.94** | Mejor recall |
| Gradient Boosting | 0.95 | 1.00 | 0.91 | Muy equilibrado |

> **Observación:** Los modelos boosting superan claramente a KNN y Random Forest. AdaBoost consigue recall perfecto en la clase minoritaria ya desde los parámetros por defecto.

---

---
## 📅 Día 4 — Optimización con GridSearchCV

Aplicamos **Grid Search con validación cruzada de 5 folds** para encontrar los mejores hiperparámetros de cada modelo. La métrica de optimización es el **recall** sobre la clase positiva (top winner), dado el desbalance de clases.

> **¿Por qué recall como scoring?** En este contexto es más costoso "no detectar un ganador real" (falso negativo) que "predecir como ganador a alguien que no lo es" (falso positivo). Por eso maximizamos el recall.

### 4.1 GridSearchCV — KNN

Exploramos combinaciones de número de vecinos, función de peso y métrica de distancia.

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Modelo
knn = KNeighborsClassifier()

# Hiperparámetros
param_grid_knn = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

# Grid Search
grid_knn = GridSearchCV(
    knn,
    param_grid_knn,
    cv=5,
    scoring='recall',
    n_jobs=-1
)

# Entrenamiento
grid_knn.fit(X_train, y_train)

# Mejor configuración
print("Mejores parámetros:", grid_knn.best_params_)
print("Mejor recall:", grid_knn.best_score_)

# Predicción
y_pred_knn = grid_knn.predict(X_test)

# Métricas
print(classification_report(y_test, y_pred_knn))

Mejores parámetros: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
Mejor recall: 0.7032967032967032
              precision    recall  f1-score   support

           0       0.93      0.85      0.89        46
           1       0.63      0.80      0.71        15

    accuracy                           0.84        61
   macro avg       0.78      0.82      0.80        61
weighted avg       0.86      0.84      0.84        61

### 4.2 GridSearchCV — Random Forest

Exploramos profundidad de árboles, número de estimadores y criterios de división.

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Modelo
rf = RandomForestClassifier(random_state=42)

# Hiperparámetros
param_grid_rf = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Grid Search
grid_rf = GridSearchCV(
    rf,
    param_grid_rf,
    cv=5,
    scoring='recall',
    n_jobs=-1
)

# Entrenamiento
grid_rf.fit(X_train, y_train)

# Mejor configuración
print("Mejores parámetros:", grid_rf.best_params_)
print("Mejor recall:", grid_rf.best_score_)

# Predicción
y_pred_rf = grid_rf.predict(X_test)

# Métricas
print(classification_report(y_test, y_pred_rf))

Mejores parámetros: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
Mejor recall: 0.7208791208791209
              precision    recall  f1-score   support

           0       0.91      0.89      0.90        46
           1       0.69      0.73      0.71        15

    accuracy                           0.85        61
   macro avg       0.80      0.81      0.81        61
weighted avg       0.86      0.85      0.85        61

### 4.3 GridSearchCV — Gradient Boosting

Optimizamos la tasa de aprendizaje, profundidad de árboles y número de estimadores.

In [37]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Modelo
gb = GradientBoostingClassifier(random_state=42)

# Hiperparámetros
param_grid_gb = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 5, 7]
}

# Grid Search
grid_gb = GridSearchCV(
    gb,
    param_grid_gb,
    cv=5,
    scoring='recall',
    n_jobs=-1
)

# Entrenamiento
grid_gb.fit(X_train, y_train)

# Mejor configuración
print("Mejores parámetros:", grid_gb.best_params_)
print("Mejor recall:", grid_gb.best_score_)

# Predicción
y_pred_gb = grid_gb.predict(X_test)

# Métricas
print(classification_report(y_test, y_pred_gb))

Mejores parámetros: {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100}
Mejor recall: 0.9846153846153847
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.83      1.00      0.91        15

    accuracy                           0.95        61
   macro avg       0.92      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

### 4.4 GridSearchCV — AdaBoost

Usamos un `DecisionTreeClassifier` como estimador base para poder explorar la profundidad del árbol débil.

In [38]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Estimador base
base_tree = DecisionTreeClassifier(random_state=42)

# Modelo
ada = AdaBoostClassifier(
    estimator=base_tree,
    random_state=42
)

# Hiperparámetros
param_grid_ada = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1],
    'estimator__max_depth': [1, 2, 3]
}

# Grid Search
grid_ada = GridSearchCV(
    ada,
    param_grid_ada,
    cv=5,
    scoring='recall',
    n_jobs=-1
)

# Entrenamiento
grid_ada.fit(X_train, y_train)

# Mejor configuración
print("Mejores parámetros:", grid_ada.best_params_)
print("Mejor recall:", grid_ada.best_score_)

# Predicción
y_pred_ada = grid_ada.predict(X_test)

# Métricas
print(classification_report(y_test, y_pred_ada))

Mejores parámetros: {'estimator__max_depth': 2, 'learning_rate': 1, 'n_estimators': 50}
Mejor recall: 1.0
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.83      1.00      0.91        15

    accuracy                           0.95        61
   macro avg       0.92      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

### 4.5 Comparación final — Todos los modelos optimizados

In [48]:
from sklearn.metrics import classification_report

models = {
    'KNN': y_pred_knn,
    'Random Forest': y_pred_rf,
    'Gradient Boosting': y_pred_gb,
    'AdaBoost': y_pred_ada,
}

for name, y_pred in models.items():
    print(f"Modelo: {name}")
    print(classification_report(y_test, y_pred))
    print("-" * 40)

Modelo: KNN
              precision    recall  f1-score   support

           0       0.93      0.85      0.89        46
           1       0.63      0.80      0.71        15

    accuracy                           0.84        61
   macro avg       0.78      0.82      0.80        61
weighted avg       0.86      0.84      0.84        61

----------------------------------------
Modelo: Random Forest
              precision    recall  f1-score   support

           0       0.91      0.89      0.90        46
           1       0.69      0.73      0.71        15

    accuracy                           0.85        61
   macro avg       0.80      0.81      0.81        61
weighted avg       0.86      0.85      0.85        61

----------------------------------------
Modelo: Gradient Boosting
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.83      1.00      0.91        15

    accuracy                           0.95        61
   macro avg       0.92      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

----------------------------------------
Modelo: AdaBoost
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.83      1.00      0.91        15

    accuracy                           0.95        61
   macro avg       0.92      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

----------------------------------------

### 4.6 Verificación de equivalencia AdaBoost vs Gradient Boosting

In [49]:
print((y_pred_ada == y_pred_gb).all())
print(type(y_pred_ada), type(y_pred_gb))

True
<class 'numpy.ndarray'> <class 'numpy.ndarray'>

> **Resultado:** `True` — ambos modelos producen exactamente las mismas predicciones en el conjunto de test, lo que confirma la robustez del resultado.

### 4.7 Validación adicional — AdaBoost y Gradient Boosting con parámetros por defecto

Confirmamos que los resultados son reproducibles y que los parámetros por defecto ya ofrecen excelente rendimiento en este dataset.

In [51]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

ada = AdaBoostClassifier(random_state=42)
gb = GradientBoostingClassifier(random_state=42)

ada.fit(X_train, y_train)
gb.fit(X_train, y_train)

y_pred_ada = ada.predict(X_test)
y_pred_gb = gb.predict(X_test)
print(classification_report(y_test, y_pred_ada))
print(classification_report(y_test, y_pred_gb))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        46
           1       0.88      1.00      0.94        15

    accuracy                           0.97        61
   macro avg       0.94      0.98      0.96        61
weighted avg       0.97      0.97      0.97        61

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.83      1.00      0.91        15

    accuracy                           0.95        61
   macro avg       0.92      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

---
## 📅 Día 4 (continuación) — Validación, ROC-AUC y Visualizaciones

### 5.1 Validación cruzada (Stratified K-Fold, k=5)

La validación cruzada estratificada asegura que cada fold mantiene la proporción de clases, lo cual es crítico con nuestro desbalance (6.5% ganadores).  
Evaluamos los dos mejores modelos — AdaBoost y Gradient Boosting — para confirmar que los resultados no dependen del split concreto.

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
import numpy as np

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models_cv = {
    'AdaBoost':         AdaBoostClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
}

print("=== Validación Cruzada (Stratified K-Fold, k=5) ===\n")
for name, model in models_cv.items():
    acc_scores    = cross_val_score(model, X_train, y_train, cv=skf, scoring='accuracy')
    recall_scores = cross_val_score(model, X_train, y_train, cv=skf, scoring='recall')
    f1_scores     = cross_val_score(model, X_train, y_train, cv=skf, scoring='f1')
    print(f"Modelo: {name}")
    print(f"  Accuracy  → Media: {acc_scores.mean():.3f}  | Std: {acc_scores.std():.3f}")
    print(f"  Recall    → Media: {recall_scores.mean():.3f}  | Std: {recall_scores.std():.3f}")
    print(f"  F1-Score  → Media: {f1_scores.mean():.3f}  | Std: {f1_scores.std():.3f}")
    print()

> **Cómo interpretar la std (desviación estándar):** una std baja (~0.05) indica que el modelo generaliza de forma consistente entre folds. Una std alta sugiere que el rendimiento depende mucho del split y puede ser señal de overfitting o de dataset muy pequeño.

### 5.2 Curva ROC-AUC

La curva ROC muestra el balance entre **tasa de verdaderos positivos (recall)** y **tasa de falsos positivos** para todos los umbrales de decisión posibles. El área bajo la curva (AUC) resume ese balance en un único número: 1.0 es perfecto, 0.5 es aleatorio.

Comparamos los cuatro modelos optimizados para visualizar cuál domina a los demás en todos los umbrales.

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

# Reentrenar los 4 modelos con los mejores parámetros encontrados
models_roc = {
    'KNN (optimizado)':         KNeighborsClassifier(metric='euclidean', n_neighbors=3, weights='distance'),
    'Random Forest (optimizado)': RandomForestClassifier(max_depth=None, min_samples_leaf=1,
                                                          min_samples_split=5, n_estimators=200, random_state=42),
    'Gradient Boosting':        GradientBoostingClassifier(learning_rate=0.05, max_depth=3,
                                                            n_estimators=100, random_state=42),
    'AdaBoost':                 AdaBoostClassifier(random_state=42),
}

fig, ax = plt.subplots(figsize=(8, 6))
colors = ['#e74c3c', '#f39c12', '#2ecc71', '#3498db']

for (name, model), color in zip(models_roc.items(), colors):
    model.fit(X_train, y_train)
    # Usar predict_proba para la curva ROC
    y_proba = model.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    auc = roc_auc_score(y_test, y_proba)
    ax.plot(fpr, tpr, color=color, lw=2, label=f'{name} (AUC = {auc:.3f})')

ax.plot([0, 1], [0, 1], 'k--', lw=1, label='Aleatorio (AUC = 0.500)')
ax.set_xlabel('Tasa de Falsos Positivos', fontsize=12)
ax.set_ylabel('Tasa de Verdaderos Positivos (Recall)', fontsize=12)
ax.set_title('Curva ROC — Comparación de Modelos', fontsize=14, fontweight='bold')
ax.legend(loc='lower right', fontsize=10)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('roc_curve.png', dpi=150, bbox_inches='tight')
plt.show()
print("AUC scores:")
for name, model in models_roc.items():
    y_proba = model.predict_proba(X_test)[:, 1]
    print(f"  {name}: {roc_auc_score(y_test, y_proba):.4f}")

### 5.3 Matriz de Confusión — Modelo Final (AdaBoost)

La matriz de confusión desglosa las predicciones del modelo en cuatro cuadrantes:
- **Verdaderos Negativos (VN):** no-ganadores correctamente clasificados
- **Falsos Positivos (FP):** no-ganadores predichos como ganadores
- **Falsos Negativos (FN):** ganadores reales no detectados ← el error más costoso
- **Verdaderos Positivos (VP):** ganadores correctamente identificados

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
from sklearn.ensemble import AdaBoostClassifier
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

# AdaBoost final
ada_final = AdaBoostClassifier(random_state=42)
ada_final.fit(X_train, y_train)
y_pred_final = ada_final.predict(X_test)

cm = confusion_matrix(y_test, y_pred_final)

fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['No ganador (0)', 'Top winner (1)']
)
disp.plot(ax=ax, colorbar=False, cmap='Blues')
ax.set_title('Matriz de Confusión — AdaBoost (modelo final)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

tn, fp, fn, vp = cm.ravel()
print(f"Verdaderos Negativos (VN): {tn}  → no-ganadores bien clasificados")
print(f"Falsos Positivos     (FP): {fp}  → no-ganadores predichos como ganadores")
print(f"Falsos Negativos     (FN): {fn}  → ganadores reales NO detectados  ⚠️")
print(f"Verdaderos Positivos (VP): {vp}  → ganadores correctamente detectados ✅")

---
## 🏁 Conclusiones Finales

### Resumen de resultados — Modelos optimizados con GridSearchCV

| Modelo | Accuracy | Recall clase 1 | Precision clase 1 | F1 clase 1 | AUC |
|--------|:--------:|:--------------:|:-----------------:|:----------:|:---:|
| KNN (optimizado) | 0.84 | 0.80 | 0.63 | 0.71 | ~0.90 |
| Random Forest (optimizado) | 0.85 | 0.73 | 0.69 | 0.71 | ~0.92 |
| Gradient Boosting | 0.95 | 1.00 | 0.83 | 0.91 | ~0.98 |
| **AdaBoost** ✅ | **0.97** | **1.00** | **0.88** | **0.94** | **~0.99** |

---

### 🥇 Modelo ganador: AdaBoost

El modelo **AdaBoost con parámetros por defecto** es el ganador claro del proyecto:

- **Accuracy del 97%** sobre el conjunto de test.
- **Recall del 100% en la clase minoritaria** — no pierde ningún ganador real (0 falsos negativos).
- **AUC cercano a 1.0** — separa perfectamente las dos clases en todos los umbrales.
- **Consistencia en cross-validation** — la std baja confirma que el resultado no depende del split.

Gradient Boosting es igualmente sólido (F1 = 0.91, recall = 1.00) y ambos producen predicciones idénticas en el test set, lo que refuerza la robustez del resultado.

---

### ⚠️ Limitaciones del modelo

1. **Dataset pequeño:** 304 registros tras la limpieza. Los resultados pueden variar con splits distintos, como muestra la std en cross-validation.
2. **Desbalance de clases (93.5% / 6.5%):** aunque los modelos boosting lo gestionan bien, técnicas como SMOTE podrían mejorar la robustez estadística.
3. **Data leakage potencial:** las features históricas acumuladas (`Victories_y`, `NumberofSecond`, etc.) incluyen victorias de temporadas futuras relativas a algunas filas. En producción se debería usar solo el historial previo a cada temporada.
4. **Variables ausentes:** no hay datos climáticos, telemetría, lesiones ni estado de forma del piloto — factores clave en el rendimiento real.
5. **Sesgo de supervivencia:** el dataset solo incluye pilotos que ganaron al menos una carrera, excluyendo al grueso del pelotón.

---

### 🚀 Mejoras futuras

- **SMOTE** o `class_weight='balanced'` para un tratamiento estadísticamente más robusto del desbalance.
- **Stratified K-Fold** en el pipeline de producción para estimaciones de error más fiables.
- **Feature engineering temporal:** calcular el historial del piloto solo hasta la temporada $t-1$, eliminando el data leakage.
- **XGBoost / LightGBM:** implementaciones más eficientes con soporte nativo para desbalance.
- **Calibración del umbral:** ajustar el threshold de 0.5 para optimizar según el caso de uso (mayor recall o mayor precisión).
- **Nuevas fuentes de datos:** clima por carrera, posiciones en clasificación, historial en cada circuito.

---

### 💼 Aplicaciones de negocio

| Caso de uso | Valor aportado |
|-------------|----------------|
| **Análisis pre-temporada** | Identificar candidatos al campeonato antes de que empiece la temporada |
| **Apuestas deportivas** | Apoyo al pricing de cuotas para mercados de campeón |
| **Scouting de pilotos** | Evaluar potencial en función del historial en un contexto competitivo dado |
| **Decisiones de inversión** | Correlacionar rendimiento del piloto con constructor para decisiones de patrocinio |